CREATE TABLE [dbo].[tSchool] (
    [Id]               INT            IDENTITY (1, 1) NOT NULL,
    [EMISNumber]       NVARCHAR (50)  NOT NULL,
    [Description]      NVARCHAR (255) NOT NULL,
    [SchoolTypeId]     INT            NOT NULL,
    [Phase]            NVARCHAR (100) NULL,
    [Level]            NVARCHAR (50)  NULL,
    [Country]          NVARCHAR (255) NOT NULL,
    [Province]         NVARCHAR (255) NOT NULL,
    [District]         NVARCHAR (255) NOT NULL,
    [Circuit]          NVARCHAR (255) NOT NULL,
    [Municipality]     NVARCHAR (255) NULL,
    [UrbanRural]       NVARCHAR (50)  NULL,
    [AddressLine1]     NVARCHAR (255) NULL,
    [AddressLine2]     NVARCHAR (255) NULL,
    [TownCity]         NVARCHAR (255) NULL,
    [PostalCode]       NVARCHAR (10)  NULL,
    [PhoneNumber]      NVARCHAR (50)  NULL,
    [Email]            NVARCHAR (100) NULL,
    [Latitude]         DECIMAL (9, 6) NULL,
    [Longitude]        DECIMAL (9, 6) NULL,
    [IsDeleted]        BIT            DEFAULT ((0)) NOT NULL,
    [CreatedBy]        NVARCHAR (255) NULL,
    [CreatedDate]      DATETIME       DEFAULT (getdate()) NOT NULL,
    [LastModifiedBy]   NVARCHAR (255) NULL,
    [LastModifiedDate] DATETIME       DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([EMISNumber] ASC)
);

